version: '3.8'
services:
  labdbpostgres:
    image: postgres:13
    restart: always
    user: "501:20"
    environment:
      POSTGRES_DB: "lab_db"
      POSTGRES_USER: "igor"
      POSTGRES_PASSWORD: "Qwerty123"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      -
        type: bind
        source: ./postgres_db
        target: /var/lib/postgresql/data
